2025-10-28 20:59:28,312 - INFO - 配置文件 '.ftp_config.json' 不存在，将引导您进行创建。
2025-10-28 21:01:00,019 - INFO - 配置已成功保存到 '.ftp_config.json'。
2025-10-28 21:01:00,024 - INFO - 检测到变更: 1 个文件待上传, 0 个文件待删除。
2025-10-28 21:01:00,426 - INFO - 成功连接到 FTP 服务器: 185.239.85.20:21
2025-10-28 21:01:00,598 - INFO - 已切换到远程目录: /api.xunanit.cn
2025-10-28 21:01:00,599 - INFO - 
--- 开始上传文件 ---
2025-10-28 21:10:30,681 - INFO - --- Auto FTP Sync v2.0 ---
2025-10-28 21:10:30,682 - INFO - 开始监控目录: D:\Code\FTP_Agent
2025-10-28 21:10:30,682 - INFO - 按 Ctrl+C 停止监控。
2025-10-28 21:11:09,780 - INFO - 检测到事件: created - D:\Code\FTP_Agent\2.py
2025-10-28 21:11:11,290 - INFO - ==================================================
2025-10-28 21:11:11,290 - INFO - 开始执行同步任务...
2025-10-28 21:11:11,296 - INFO - 检测到变更: 3 个文件待上传, 0 个文件待删除。
2025-10-28 21:11:13,050 - INFO -   [上传成功] D:\Code\FTP_Agent\1.py -> 1.py
2025-10-28 21:11:14,693 - INFO - 检测到事件: modified - D:\Code\FTP_Agent\2.py
2025-10-28 21:11:14,694 - INFO - 检测到事件: modified - D:\Code\FTP_Agent\2.py
2025-10-28 21:11:14,694 - INFO - 检测到事件: modified - D:\Code\FTP_Agent\2.py
2025-10-28 21:11:16,202 - INFO - ==================================================
2025-10-28 21:11:16,203 - INFO - 开始执行同步任务...
2025-10-28 21:11:16,205 - INFO - 检测到变更: 3 个文件待上传, 0 个文件待删除。
2025-10-28 21:11:16,604 - ERROR - FTP 连接失败: 421 Too many connections (10) from this IP
2025-10-28 21:15:00,367 - INFO - 监控已停止。
2025-10-28 21:16:00,925 - ERROR -   [上传失败] .\sync.py -> sync.py: 421 Timeout
